[versions]
# Library and plugin version
kotlin = "2.3.0"
agp = "8.13.2"
composeMultiplatform = "1.10.0-rc02"
mavenPublish = "0.35.0"

# library module's configuration information
library-group = "io.github.sudarshanmhasrup.hellokmp"
library-artifactId = "hello-kmp"
library-version = "1.0.0"

# library module's android library package information
library-androidLibrary-namespace = "io.github.sudarshanmhasrup.hellokmp"
library-androidLibrary-compileSdk = "36"
library-androidLibrary-minSdk = "21"

# shared module's configuration information
shared-group = "com.hellokmp.shared"
shared-version = "1.0.0"

# shared module's android library package information
shared-androidLibrary-namespace = "com.hellokmp.shared"
shared-androidLibrary-compileSdk = "36"
shared-androidLibrary-minSdk = "21"

# desktop module's configuration information
desktop-group = "com.hellokmp.app"
desktop-version = "1.0.0"
desktop-mainClass = "com.hellokmp.app.MainKt"

# desktop module's distribution information
desktop-packageName = "HelloKMP"
desktop-packageVersion = "1.0.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }