[versions]
# Library and plugin version
kotlin = "2.3.0"
agp = "8.13.2"
mavenPublish = "0.35.0"

# library module's configuration information
library-group = "io.github.sudarshanmhasrup.hellokmp"
library-artifactId = "hello-kmp"
library-version = "1.0.0"

# library module's android library package information
library-androidLibrary-namespace = "io.github.sudarshanmhasrup.hellokmp"
library-androidLibrary-compileSdk = "36"
library-androidLibrary-minSdk = "21"

[libraries]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }